FROM alpine:3.12
LABEL maintainer="Angga Lanuma <lanuma.angga@gmail.com>"

# RUN apk --no-cache --update add build-base

RUN apk add --no-cache build-base git openssh \
                       nodejs npm bash curl \
                       rsync kubectl

WORKDIR /app


